GET http://localhost:3000/test

###
Get http://localhost:3000/library

###

DELETE http://localhost:3000/library/2
###


POST http://localhost:3000/library/create
Content-Type: application/json

{
  "isbn": "978-3-16-148410-0",
  "anzahl": 5,
  "entlehnung": "2025-10-03T13:00:00",
  "verlag": "Springer",
  "jahr": 2022,
  "titel": "Node.js für Einsteiger",
  "status": "verfügbar",
  "bild": "cover.jpg",
  "administrator": 1,
  "sid": 1,
  "autor": "Max Mustermann",
  "kid": 3,
  "beschreibung": "Ein Buch über Node.js"
}

